# I comment out the port parts because network is "caddy"

services:
  teable:
    image: ghcr.io/teableio/teable:latest
    restart: always
#    ports:
#      - '127.0.0.1:3001:3000'
    volumes:
      - ./teable-data:/app/.assets:rw
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE}
      - NEXT_ENV_IMAGES_ALL_REMOTE=true
    networks:
      - teable-standalone
      - caddy
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      teable-db-migrate:
        condition: service_completed_successfully

  teable-db:
    image: postgres:15.4
    restart: always
#    ports:
#      - '127.0.0.1:42345:5432'
    volumes:
      - ./teable-db:/var/lib/postgresql/data:rw
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - teable-standalone
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  teable-db-migrate:
    image: ghcr.io/teableio/teable-db-migrate:latest
    environment:
      - TZ=${TIMEZONE}
      - PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    networks:
      - teable-standalone
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      teable-db:
        condition: service_healthy

networks:
  caddy:
    name: caddy
    external: true
  teable-standalone:
    name: teable-standalone-network
    driver: bridge
    internal: true
